version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "lopes"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lopes"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
    reviewers:
      - "lopes"
