version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jose.lopes"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jose.lopes"
